### ISSUE TITLE
Starting service puppetserver is failing because of lack of memory

### ISSUE THREAD

**Issue by pitarch** [pitarch/pittlab-puppet-with-vagrant#6]
```
2018-03-18 11:07:50,280 ERROR [async-dispatch-2] [p.t.internal] Error during service init!!!
java.lang.Error: Not enough available RAM (488MB) to safely accommodate the configured JVM heap size of 1,979MB. Puppet Server requires at least 2,177MB of available RAM given this heap size, computed as 1.1 * max heap (-Xmx). Either incr
ease available memory or decrease the configured heap size by reducing the -Xms and -Xmx values in JAVA_ARGS in /etc/sysconfig/puppetserver on EL systems or /etc/default/puppetserver on Debian systems.
        at puppetlabs.services.master.master_core$validate_memory_requirements_BANG_.invokeStatic(master_core.clj:834)
        at puppetlabs.services.master.master_core$validate_memory_requirements_BANG_.invoke(master_core.clj:821)
        at puppetlabs.services.master.master_service$reify__38789$service_fnk__5266__auto___positional$reify__38814.init(master_service.clj:95)
        at puppetlabs.trapperkeeper.services$eval5068$fn__5069$G__5056__5072.invoke(services.clj:9)
```

**Comment by pitarch** [comment]
solved at issue #4
